# Generated by Django 5.2.1 on 2025-05-14 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Drawings/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Pencil', 'Pencil'), ('Charcoal', 'Charcoal'), ('Watercolor', 'Watercolor'), ('Oil', 'Oil'), ('Acrylic', 'Acrylic'), ('Digital', 'Digital'), ('Mixed Media', 'Mixed Media')], max_length=50)),
            ],
        ),
    ]
