# Generated by Django 5.2.1 on 2025-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawings', '0005_remove_alldrawing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldrawing',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
