# Generated by Django 5.2.1 on 2025-05-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawings', '0007_alter_alldrawing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldrawing',
            name='description',
            field=models.CharField(default=''),
        ),
    ]
