# Generated by Django 5.2.1 on 2025-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawings', '0010_alldrawing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldrawing',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
